---
title: "Hankowsky_HW1"
author: "Keith Hankowsky"
date: '2022-09-09'
output: html_document
---

```{r, include = FALSE}
library(Sleuth3)
library(tidyverse)
```


#Hankowsky Homework Solutions 

# Basic Problems
## 1.21



## 1.27
```{r}
#pulling the data from the 'Sleuth 3' package 
senate <- Sleuth3::ex0127

```



# Supplemental Problems 
## 1.16 (Sleuth 2nd Edition)
### A
```{r}
#A
#pull the data from the 'Sleuth 2' package so I don't have to enter it manually
planets <- Sleuth2::ex0116
```

### B
```{r}
#B
#plotting the distance from sun vs planet order 
planets %>%
  mutate(Order = as.factor(Order)) %>%
  ggplot() + 
  geom_point(aes(x = Order, y = Distance)) + 
  geom_text(aes(x = Order, y = Distance, label = Planet), hjust = 0, nudge_x = 0.09) + 
  scale_x_discrete(breaks = seq(0,10,1)) + 
  labs(x = "Planet Order", y = "Distance from Sun") + 
  theme_classic()
```

### C
```{r}
#C
#plotting the natural log of distance from sun vs planet order
planets %>%
  mutate(Order = as.factor(Order)) %>%
  mutate(log_distance = log(Distance)) %>%
  ggplot() + 
  geom_point(aes(x = Order, y = log_distance)) +
  geom_text(aes(x = Order, y = log_distance, label = Planet), hjust = 0, nudge_x = 0.09) + 
  scale_x_discrete(breaks = seq(0,10,1)) + 
  labs(x = "Planet Order", y = "ln(Distance from Sun)") + 
  theme_classic()

```

### D
```{r}
#D
summary(planets$Distance)

sd(planets$Distance)

```

### E
```{r}
#E
planets <- planets %>%
  mutate(log_distance = log(Distance))

summary(planets$log_distance)

sd(planets$log_distance)
```



## 1.26b (Sleuth 2nd Edition)
```{r}
library(aplpack)

Group_a <- c(1.31, 1.45, 1.12, 1.16, 1.30, 1.50, 1.20, 1.22, 1.42, 1.14, 1.23, 1.59, 
             1.11, 1.10, 1.53, 1.52, 1.17, 1.49, 1.62, 1.29)
  
Group_b <- c(1.13, 1.71, 1.39, 1.15, 1.33, 1.00, 1.03, 1.68, 1.76, 1.55, 1.34, 1.47, 
             1.74, 1.74, 1.19, 1.15, 1.20, 1.59, 1.47)

stem.leaf.backback(Group_a, Group_b, m = 1)
```


